# Generated by Django 5.2.17 on 2026-09-28 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(unique=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("currency", models.CharField(default="NGN", max_length=3)),
                (
                    "max_whatsapp_numbers",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_team_members",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "max_knowledge_documents",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "monthly_conversations",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "monthly_ai_responses",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "features",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='e.g. {"rag": true, "tools": false}',
                    ),
                ),
                ("is_public", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRIALING", "Trialing"),
                            ("ACTIVE", "Active"),
                            ("PAST_DUE", "Past Due"),
                            ("CANCELED", "Canceled"),
                        ],
                        default="TRIALING",
                        max_length=16,
                    ),
                ),
                ("current_period_start", models.DateTimeField(blank=True, null=True)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="Payment provider subscription id.",
                        max_length=128,
                    ),
                ),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to="tenants.business",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="billing.plan",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("period", models.DateField(help_text="First day of the month.")),
                ("conversations", models.PositiveIntegerField(default=0)),
                ("resolved_conversations", models.PositiveIntegerField(default=0)),
                ("messages_in", models.PositiveIntegerField(default=0)),
                ("messages_out", models.PositiveIntegerField(default=0)),
                ("ai_responses", models.PositiveIntegerField(default=0)),
                ("human_responses", models.PositiveIntegerField(default=0)),
                ("escalations", models.PositiveIntegerField(default=0)),
                ("tool_calls", models.PositiveIntegerField(default=0)),
                ("input_tokens", models.PositiveBigIntegerField(default=0)),
                ("output_tokens", models.PositiveBigIntegerField(default=0)),
                ("cache_read_tokens", models.PositiveBigIntegerField(default=0)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "ordering": ["-period"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business", "period"), name="unique_usage_period"
                    )
                ],
            },
        ),
    ]
