# Generated by Django 5.2.17 on 2026-09-28 16:21

import common.fields
import django.db.models.deletion
import knowledge.models
from django.db import migrations, models


def enable_pgvector(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute("CREATE EXTENSION IF NOT EXISTS vector")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(enable_pgvector, migrations.RunPython.noop),
        migrations.CreateModel(
            name="KnowledgeDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("FILE", "File"),
                            ("TEXT", "Text"),
                            ("URL", "Url"),
                            ("FAQ", "Faq"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        blank=True, upload_to=knowledge.models.document_upload_path
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                (
                    "raw_text",
                    models.TextField(
                        blank=True,
                        help_text="Pasted text / FAQ, or the extracted text.",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("READY", "Ready"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=12,
                    ),
                ),
                ("error", models.TextField(blank=True)),
                ("chunk_count", models.PositiveIntegerField(default=0)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="KnowledgeChunk",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField()),
                ("content", models.TextField()),
                ("embedding", common.fields.EmbeddingField(null=True)),
                ("embedding_model", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.business",
                    ),
                ),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chunks",
                        to="knowledge.knowledgedocument",
                    ),
                ),
            ],
            options={
                "ordering": ["document_id", "index"],
                "indexes": [
                    models.Index(
                        fields=["business", "document"],
                        name="knowledge_k_busines_10eb5c_idx",
                    )
                ],
            },
        ),
    ]
