# Generated by Django 5.2.17 on 2026-09-28 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("knowledge", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="knowledgedocument",
            name="max_pages",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="For URLs: crawl up to this many pages on the same site (1 = just this page).",
            ),
        ),
    ]
