# Generated by Django 5.2.17 on 2026-09-28 16:51

import conversations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("conversations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="media",
            field=models.FileField(
                blank=True, upload_to=conversations.models.message_media_path
            ),
        ),
        migrations.AddField(
            model_name="message",
            name="media_mime_type",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="conversation",
            name="channel",
            field=models.CharField(
                choices=[("WHATSAPP", "Whatsapp"), ("SANDBOX", "Sandbox")],
                default="WHATSAPP",
                max_length=16,
            ),
        ),
    ]
