# Generated by Django 5.2.17 on 2026-09-28 16:21

import chatbot.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIConfiguration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "enabled",
                    models.BooleanField(
                        default=True,
                        help_text="Turn the AI off to route everything to humans.",
                    ),
                ),
                (
                    "template",
                    models.SlugField(
                        blank=True, help_text="Template this bot was created from."
                    ),
                ),
                ("name", models.CharField(default="Assistant", max_length=100)),
                (
                    "system_prompt",
                    models.TextField(
                        blank=True,
                        help_text="Business-specific instructions: personality, responsibilities, policies.",
                    ),
                ),
                (
                    "model",
                    models.CharField(
                        default=chatbot.models.default_model, max_length=100
                    ),
                ),
                (
                    "max_tokens",
                    models.PositiveIntegerField(
                        default=4096,
                        validators=[
                            django.core.validators.MinValueValidator(256),
                            django.core.validators.MaxValueValidator(32000),
                        ],
                    ),
                ),
                (
                    "effort",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Model default"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="",
                        max_length=8,
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        default="auto",
                        help_text='"auto" replies in the customer\'s language.',
                        max_length=50,
                    ),
                ),
                ("welcome_message", models.TextField(blank=True)),
                (
                    "fallback_message",
                    models.TextField(
                        default="Sorry, I'm having trouble answering right now. A team member will get back to you shortly."
                    ),
                ),
                ("human_handoff_enabled", models.BooleanField(default=True)),
                ("rag_enabled", models.BooleanField(default=True)),
                ("memory_enabled", models.BooleanField(default=True)),
                (
                    "history_limit",
                    models.PositiveSmallIntegerField(
                        default=20,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "business",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_config",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
