# Generated by Django 5.2.17 on 2026-09-28 16:51

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="mfa_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_last_counter",
            field=models.BigIntegerField(
                blank=True, help_text="Prevents code replay.", null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_recovery_codes",
            field=models.JSONField(
                blank=True, default=list, help_text="SHA-256 hashes of unused codes."
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="mfa_secret",
            field=common.fields.EncryptedTextField(blank=True),
        ),
    ]
