# Generated by Django 5.2.17 on 2026-09-28 16:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone_number",
                    models.CharField(
                        help_text="E.164 digits, as reported by WhatsApp.",
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "external_id",
                    models.CharField(
                        blank=True,
                        help_text="ID in the business's own CRM.",
                        max_length=128,
                    ),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["business", "-updated_at"],
                        name="customers_c_busines_8d5c00_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business", "phone_number"),
                        name="unique_customer_phone_per_business",
                    )
                ],
            },
        ),
    ]
