# Generated by Django 5.2.17 on 2026-09-28 16:21

import common.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WhatsAppAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("display_name", models.CharField(blank=True, max_length=200)),
                (
                    "phone_number",
                    models.CharField(
                        help_text="Display phone number, e.g. +2348012345678.",
                        max_length=32,
                    ),
                ),
                (
                    "phone_number_id",
                    models.CharField(
                        help_text="Meta phone number ID.", max_length=64, unique=True
                    ),
                ),
                (
                    "business_account_id",
                    models.CharField(
                        help_text="WhatsApp Business Account (WABA) ID.", max_length=64
                    ),
                ),
                (
                    "access_token",
                    common.fields.EncryptedTextField(
                        help_text="System-user access token; encrypted at rest."
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("ACTIVE", "Active"), ("DISABLED", "Disabled")],
                        default="ACTIVE",
                        max_length=16,
                    ),
                ),
                ("last_webhook_at", models.DateTimeField(blank=True, null=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
