# Generated by Django 5.2.17 on 2026-09-28 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0002_business_brand_color_business_brand_name_and_more"),
        ("whatsapp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("external_id", models.CharField(blank=True, max_length=64)),
                ("name", models.CharField(max_length=512)),
                ("language", models.CharField(max_length=16)),
                ("category", models.CharField(blank=True, max_length=32)),
                (
                    "status",
                    models.CharField(
                        help_text="APPROVED, PENDING, REJECTED, PAUSED...",
                        max_length=32,
                    ),
                ),
                ("components", models.JSONField(blank=True, default=list)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.business",
                    ),
                ),
                (
                    "whatsapp_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="templates",
                        to="whatsapp.whatsappaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "language"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("whatsapp_account", "name", "language"),
                        name="unique_template_per_number",
                    )
                ],
            },
        ),
    ]
