# Generated by Django 5.2.17 on 2026-09-28 16:21

import common.fields
import django.core.validators
import django.db.models.deletion
import tools.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z][a-z0-9_]{0,63}$",
                                "Use lowercase letters, digits and underscores (e.g. check_order_status).",
                            )
                        ],
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        help_text="Tells the AI when and how to use this tool."
                    ),
                ),
                (
                    "input_schema",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text='JSON Schema for the arguments, e.g. {"type":"object","properties":{"order_id":{"type":"string"}},"required":["order_id"]}',
                    ),
                ),
                ("endpoint_url", models.URLField()),
                (
                    "http_method",
                    models.CharField(
                        choices=[("POST", "Post"), ("GET", "Get")],
                        default="POST",
                        max_length=8,
                    ),
                ),
                (
                    "signing_secret",
                    common.fields.EncryptedTextField(
                        default=tools.models.generate_signing_secret
                    ),
                ),
                ("timeout_seconds", models.PositiveSmallIntegerField(default=10)),
                ("enabled", models.BooleanField(default=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="tenants.business",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("business", "name"),
                        name="unique_tool_name_per_business",
                    )
                ],
            },
        ),
    ]
